### ISSUE TITLE
Implement VJP for Clone

### ISSUE THREAD

**Issue by tfogal** [Lightning-AI/lightning-thunder#1068]
## 🚀 Model / language coverage

```
VJP for t0 = prims.clone(a)  # t0: "cuda:0 f32[22, 2, 480, 640]" is not implemented
Traceback (most recent call last):
  File "/home/tfogal/dev/proxy/test.py", line 141, in <module>
    test_model_speed(args.num_steps, args.batch_size, args.fp16, args.split_gconv, args.benchmark, args.compile, args.dataloc)
  File "/home/tfogal/dev/proxy/test.py", line 121, in test_model_speed
    warmup_loop(2, m, fp16, optimizer, scaler, loss_fn, input, target, local_rank, dataloc)
  File "/home/tfogal/dev/proxy/test.py", line 31, in warmup_loop
    output = m(input_data)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/module.py", line 80, in forward
    res = self._forward_fn(*args, **kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/__init__.py", line 745, in fn_
    cache_entry, inps, pro_to_epi = get_computation_and_inputs(*args, **kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/langctxs.py", line 136, in _fn
    result = fn(*args, **kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/__init__.py", line 230, in cache_info_wrapper
    res = fn(*args, **kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/__init__.py", line 661, in get_computation_and_inputs
    computation_trc, backward_trc = split_forward_backward(computation_trc, cd, cs, *inps)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/executors/torch_autograd.py", line 137, in split_forward_backward
    fw_trace, bw_trace = forward_and_backward_from_trace(primal_trace, torch_autograd=True)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/transforms.py", line 3687, in forward_and_backward_from_trace
    forward_trace = construct_trace()(augmented_forward_fn, *trace.args, **trace.kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/interpreter.py", line 1317, in fn_
    return fn(*args, **kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/common.py", line 564, in _trace
    result = fn(*proxyargs, **proxykwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/transforms.py", line 3657, in augmented_forward_fn
    result, env = augmented_forward_pass(*args, trace=trace, **kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/transforms.py", line 3263, in augmented_forward_pass
    result, env = eval_trace(
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/transforms.py", line 1500, in eval_trace
    result = prim_func(*args, **kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/transforms.py", line 3203, in _vjp_impl
    out_primal, out_residuals = vjp_impl(*primals, **kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/transforms.py", line 2992, in decomposed_fn_aug_fwd_rule
    result, env = augmented_forward_pass(*args, trace=trace, **kwargs)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/transforms.py", line 3263, in augmented_forward_pass
    result, env = eval_trace(
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/transforms.py", line 1497, in eval_trace
    prim_func = symbol_mapper(symbol)
  File "/home/tfogal/env/lib/python3.10/site-packages/thunder/core/transforms.py", line 3199, in vjp_symbol_mapper
    raise NotImplementedError(f"VJP for {symbol.sym.id} is not implemented")
NotImplementedError: VJP for PrimIDs.CLONE is not implemented
```

### Minimal Repro

**Comment by t-vi** [comment]
PyTorch just returns the output, at least not when using vanilla clone:
```python
In [1]: import torch

In [2]: a = torch.randn(5, 5)

In [3]: a = torch.randn(5, 5, requires_grad=True)

In [4]: b = a.clone()

In [5]: b
Out[5]: 
tensor([[ 0.9325, -0.9590,  0.4283, -0.1093, -1.2395],
        [-0.2284, -1.3897,  0.5973, -0.4723, -0.1752],
        [ 0.7622,  0.9047,  0.3798, -0.7552,  0.7794],
        [-1.0699, -1.8410, -0.2015,  1.4480, -0.0367],
        [ 0.0426,  0.9618,  0.0020, -0.4464,  0.7840]],
       grad_fn=<CloneBackward0>)

In [6]: gr_out = torch.randn_like(b)

In [7]: gr_out
Out[7]: 
tensor([[ 0.0970, -0.2468,  0.2483,  0.1379,  2.3453],
        [ 2.0550,  0.3495,  2.1799, -0.4032, -0.6670],
        [-0.3441, -0.5292, -1.4925, -0.8962, -1.7581],
        [-0.7897, -0.4453, -1.3610,  1.0941,  1.2652],
        [ 0.4160,  1.6167,  0.0787, -0.7377,  2.7038]])

In [8]: gr_in, = torch.autograd.grad(b, [a], gr_out)

In [9]: gr_in
Out[9]: 
tensor([[ 0.0970, -0.2468,  0.2483,  0.1379,  2.3453],
        [ 2.0550,  0.3495,  2.1799, -0.4032, -0.6670],
        [-0.3441, -0.5292, -1.4925, -0.8962, -1.7581],
        [-0.7897, -0.4453, -1.3610,  1.0941,  1.2652],
        [ 0.4160,  1.6167,  0.0787, -0.7377,  2.7038]])

In [10]: id(gr_in)
Out[10]: 139796249897648

In [11]: id(gr_out)
Out[11]: 139796249897648
```

**Comment by IvanYashchuk** [comment]
There are two tutorials about defining backward for operators:
1. https://github.com/Lightning-AI/lightning-thunder/blob/main/notebooks/dev_tutorials/thunder-add-vjp-rule.md
2. https://github.com/Lightning-AI/lightning-thunder/blob/main/notebooks/adding_custom_operator_backward.ipynb

In addition to that, there are plenty of examples in [thunder/core/transforms.py](https://github.com/Lightning-AI/lightning-thunder/blob/main/thunder/core/transforms.py) (search for `register_grad` or `register_augmented_forward`&`register_backward`).

There's no OpInfo for `prims.clone`, once it's added to [thunder/tests/opinfos.py](https://github.com/Lightning-AI/lightning-thunder/blob/main/thunder/tests/opinfos.py) the tests for newly added backward definition will be autogenerated. Another way to to trigger test generation is to add an entry to this list:
https://github.com/Lightning-AI/lightning-thunder/blob/29ffb4394d479663cbb975607d7bcc95b865dc59/thunder/tests/test_grad.py#L57
