### ISSUE TITLE
Investigate why we cannot use TransformerEngine executor when thunder is used as torch.compile backend

### ISSUE THREAD

**Issue by crcrpar** [Lightning-AI/lightning-thunder#1137]
rel: https://github.com/Lightning-AI/lightning-thunder/blob/5846ef03814d2d47203b87aaf17e813a85d7b915/thunder/benchmarks/benchmark_litgpt.py#L580-L592

**Comment by kshitij12345** [comment]
Grabbing for investigation

**Comment by kshitij12345** [comment]
After applying the following patch to remove the ValueError,

<details>

```patch
diff --git a/thunder/benchmarks/benchmark_litgpt.py b/thunder/benchmarks/benchmark_litgpt.py
index f63a66f5..a71b659d 100644
--- a/thunder/benchmarks/benchmark_litgpt.py
+++ b/thunder/benchmarks/benchmark_litgpt.py
@@ -575,19 +575,7 @@ class Benchmark_litGPT:
                     import torch._dynamo.config as dynamo_config
 
                     dynamo_config.cache_size_limit = 64
-                    if "transformerengine" in self.compile:
-                        # [rank0]:   File "/opt/pytorch/lightning-thunder/thunder/executors/transformer_engineex.py", line 410, in _te_functional_linear_backward_impl
-                        # [rank0]:     grads = _Linear.backward(ctx, g)
-                        # [rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/module/linear.py", line 449, in backward
-                        # [rank0]:     weight_fp8.transpose_2d(),
-                        # [rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/float8_tensor.py", line 625, in transpose_2d
-                        # [rank0]:     if self._transpose is None:
-                        # [rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/float8_tensor.py", line 39, in get_func
-                        # [rank0]:     return self._fp8_attrs[name]
-                        # [rank0]: AttributeError: 'Float8Tensor' object has no attribute '_fp8_attrs'
-                        raise ValueError(
-                            "TransformerEngine executor cannot be used as an executor of Thunder when Thunder is used as torch.compile backend"
-                        )
+
                 backend = ThunderCompiler(executors=executors)
                 # Because Lightning Fabric is imported in this script it monkey patches the torch.compile function
                 # https://github.com/Lightning-AI/pytorch-lightning/blob/828fd998961f6a60f92c35254bb94d6e049ad069/src/lightning/fabric/wrappers.py#L421
```

</details>


Running on latest main (and https://github.com/Lightning-AI/lightning-thunder/commit/87e0cdf3e3aa0695a5344c989dc5bf6d9b34ebef onwards) works. It fails for commits before 87e0cdf3e3aa0695a5344c989dc5bf6d9b34ebef with `AttributeError: 'Float8Tensor' object has no attribute '_fp8_attrs'` (as noted in the issue)

Command
```bash
 torchrun --nproc_per_node=2 --no-python python thunder/benchmarks/benchmark_litgpt.py --model_name Llama-2-7b-hf --distributed_mode fsdp2 --shard_mode zero3 --compile dynamo_thunder --checkpoint_activations True --low_precision_mode fp8-delayed-te --micro_batch_size 1  --n_layer 2
```

So it seems like it is fixed now.

Will investigate more on why it was failing previously.

**Comment by kshitij12345** [comment]
Here is a smaller repro
```python
import torch
import thunder
import thunder.dynamo
from thunder.executors.transformer_engineex import transformer_engine_ex
from torch.testing._internal.logging_tensor import LoggingTensor
import sys


def forward(x, weight):
    x_1 = x + x.mean(0)

    x_1 = x_1.to(dtype = torch.bfloat16)

    return torch._C._nn.linear(x_1, weight, None)

with torch.device("cuda"):
    x = torch.randn([1, 16, 16], dtype=torch.bfloat16, requires_grad=True)
    weight = torch.randn([16, 16], dtype=torch.bfloat16, requires_grad=True)

jforward = thunder.jit(forward, executors=[transformer_engine_ex,])

o = jforward(x, weight)

# print(thunder.last_traces(jforward)[-1])

attrs = o.grad_fn.saved_tensors[4].__dict__  # This surprisingly gets cleared from the Float8Tensor instance.

print("FP8 ATTRS", o.grad_fn.saved_tensors[4]._fp8_attrs)  # Prints the dict.
print("DICT ID", id(attrs))  # Note the id of this dict
print("TENSOR ID", id(o.grad_fn.saved_tensors[4]))  # Note the id of tensor

sys.stdout.flush()

import gc
# gc.set_debug(gc.DEBUG_SAVEALL)
gc.collect()

# Uncomment gc.set_debug
# for g in gc.garbage:
#     if id(g) == id(o.grad_fn.saved_tensors[3]):
#         print("SAVED TENSOR IN GARBAGE?")  # With gc DEBUG, this doesn't print
#     if id(g) == id(o.grad_fn.saved_tensors[4]):
#         print("SAVED TENSOR FP8 IN GARBAGE?")  # With gc DEBUG, this prints - why is this tensor collected?
#     if id(g) == id(attrs):
#         print(g)

print("GC COLLECTED")

sys.stdout.flush()
# print(attrs)  # We still have reference to attrs
# print(sys.getrefcount(attrs))
# print(sys.getrefcount(o.grad_fn.saved_tensors[4]))
print("DICT ID", id(o.grad_fn.saved_tensors[4].__dict__), o.grad_fn.saved_tensors[4].__dict__)  # But this has changed (and is empty {})
print("TENSOR ID", id(o.grad_fn.saved_tensors[4]))  # This stays the same.
print("FP8 ATTRS AFTER GC", o.grad_fn.saved_tensors[4]._fp8_attrs)  # Fails here with _fp8_attrs not found.

# o.sum().backward()  # Fails here with _fp8_attrs not found.
```

Which errors with
```python
Traceback (most recent call last):
  File "/home/kkalambarkar/lightning-thunder/scratchpad/test_fp8_early_free.py", line 58, in <module>
    print("FP8 ATTRS AFTER GC", o.grad_fn.saved_tensors[4]._fp8_attrs)
AttributeError: 'Float8Tensor' object has no attribute '_fp8_attrs'
```

I am not really sure what is happening here, it looks to me that calling gc.collect clears the `__dict__` on a Float8Tensor (which has been saved for backward). And post the collection, if we try to fetch it, we get the same PyObject for the Float8Tensor but it has a new empty dict (based on the id(dict)).

Could this be related to PyObject resurrection in PyTorch https://github.com/pytorch/pytorch/issues/55686?

Also, to test if `gc.collect` is causing the issue, I tried to run the model (with 20 layers) from #1148, it works if we call `gc.disable()` at the top of the script and fails otherwise with the expected `'Float8Tensor' object has no attribute '_fp8_attrs'``

**Comment by kshitij12345** [comment]
This looks to be a PyTorch issue as I was able to repro with just PyTorch. Have filed an issue at https://github.com/pytorch/pytorch/issues/136358

**Comment by crcrpar** [comment]
> Running on latest main (and [87e0cdf](https://github.com/Lightning-AI/lightning-thunder/commit/87e0cdf3e3aa0695a5344c989dc5bf6d9b34ebef) onwards) works.

would you happen to have some idea why the commit makes such difference?
I'm wondering why splitter seems to affect the thunder's behavior to litgpt models, as I thought litgpt models do not need splitter for most cases

**Comment by kshitij12345** [comment]
> I'm wondering why splitter seems to affect the thunder's behavior to litgpt models, as I thought litgpt models do not need splitter for most cases

There were a couple of problem with splitter leading to splits for litgpt models which were fixed https://github.com/Lightning-AI/lightning-thunder/pull/1159 https://github.com/Lightning-AI/lightning-thunder/pull/1152, so there shouldn't be splits for the litgpt models now.

However, I am still trying to understand the underlying issue (still reproducible on main) which can be produced with just `thunder.jit` invocation - https://github.com/Lightning-AI/lightning-thunder/issues/1137#issuecomment-2362249945

**Comment by kshitij12345** [comment]
Thanks to @crcrpar's observation of when we comment `x_1 = x_1.to(dtype = torch.bfloat16)`, the numbers of objects collected by `gc.collect` is around 1k while with that line present it is around 3k.

So I checked whether the FP8 Tensor or it's ancestor is in a reference cycle or not. With the failing case, we see around 42 cycles (many of which are similar). If we comment `x_1 = x_1.to(dtype = torch.bfloat16)`, then we don't see any cycle and things work fine. I am not sure if these cycles being present lead to the FP8 tensor being cleared out as C++ side of PyTorch seems to still have a strong reference to the tensor.

```python
import torch
import thunder
import thunder.dynamo
from thunder.executors.transformer_engineex import transformer_engine_ex
import transformer_engine
import gc
gc.disable()

def forward(x, weight):
    x_1 = x

    x_1 = x_1.to(dtype = torch.bfloat16)  # Just comment this or call a no-op `view` like below is fine.
    # x_1 = x_1.view(x.shape)  # No cycles found in this case and everything works

    return torch._C._nn.linear(x_1, weight, None)

with torch.device("cuda"):
    x = torch.randn([1, 16, 16], dtype=torch.bfloat16, requires_grad=True)
    weight = torch.randn([16, 16], dtype=torch.bfloat16, requires_grad=True)

jforward = thunder.jit(forward, executors=[transformer_engine_ex,])

o = jforward(x, weight)

import refcycle

# Find and save cycles.
# idx = 0
# snap = refcycle.snapshot()
# for s in snap:
#     if type(s) == transformer_engine.pytorch.float8_tensor.Float8Tensor:
#         for anc in snap.ancestors(s):
#             try:
#                 cycle = snap.shortest_cycle(anc)
#                 cycle.export_image(f"fp8_cycles/fp8_cycle_{idx}.png")
#                 idx += 1
#                 print(idx)
#             except Exception:
#                 pass

# del snap, cycle

print("CALLING GC"*8, "\n")
print(f"GC collected {gc.collect()} objects")
print("GC COLLECTED"*8, "\n")

print("FP8 ATTRS AFTER GC", o.grad_fn.saved_tensors[4]._fp8_attrs)

```

Following cycles seem to be the unique cycles found - 
![fp8_cycle_38](https://github.com/user-attachments/assets/a30c6792-1bba-412d-83c8-a55d79462f36)
![fp8_cycle_3](https://github.com/user-attachments/assets/cad47fed-c1d9-4464-b917-0316f25a6b3f)
![fp8_cycle_0](https://github.com/user-attachments/assets/8bd51f17-7d23-4778-b787-e3db1e9e5201)
![fp8_cycle_41](https://github.com/user-attachments/assets/3dc608b0-b315-4838-8ff9-e6aed66a1ca0)

**Comment by t-vi** [comment]
@kshitij12345 happened to chat me up on this, so my strategy would be:

We can't do much about f_back without trickery, so we want to find the other point in the cycle.
In the lower cycle, it is line `interpreter.py:6848` holding on to `current_exception` and `e` and `tb`.
In this case, the line is the context manager, so it is a bit of a lie.

https://github.com/Lightning-AI/lightning-thunder/blob/90e3d7a64caf1d85d21e90446b187cc5fd0cf378/thunder/core/interpreter.py#L6848

It does not happen there, but on `return` or exception leaving this context manager block. From casual reading, the prime candidate will be

https://github.com/Lightning-AI/lightning-thunder/blob/90e3d7a64caf1d85d21e90446b187cc5fd0cf378/thunder/core/interpreter.py#L6981-L6987

this also needs to del the runtimectx itself, likely.

Another helpful thing might be that
```
raise e
```
can be rewritten as
```
# raise e without leaking it in the frame's f_locals.
try:
   raise e
except Exception:
   del e
   raise
```
to get rid of the local reference to e. (I thought I had handled most of these in interpreter.py though.)
