### ISSUE TITLE
Distributed notebook is failing in Ci

### ISSUE THREAD

**Issue by mruberry** [Lightning-AI/lightning-thunder#1162]
Example link: https://dev.azure.com/Lightning-AI/Tutorials/_build/results?buildId=215298&view=logs&j=a979dc62-3272-5c6a-e237-f4ca2611251c&t=7f7494f0-3c11-5ab5-a590-4f12feb12df0

Relevant snippet:

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-execute", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/cli.py", line 161, in initialize
    self.run_notebook(path)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/cli.py", line 215, in run_notebook
    client.execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
```

cc @apaz-cli @borda @carmocca @crcrpar

**Comment by t-vi** [comment]
fixed in #1161
