### ISSUE TITLE
KeyError on fusion remat when using saved for backward remat

### ISSUE THREAD

**Issue by riccardofelluga** [Lightning-AI/lightning-thunder#1203]
## 🐛 Bug

When using the saved for backward rematerialization, symbols are copied from the backward trace to forward trace and this seems to confuse the fusion rematerialization logic. In particular, the graph cut seems to contain extra information that get's in the way when calling the method `order_proxies` here:

https://github.com/Lightning-AI/lightning-thunder/blob/90e3d7a64caf1d85d21e90446b187cc5fd0cf378/thunder/core/rematerialization.py#L189

### To Reproduce

Run: 

`python thunder/benchmarks/benchmark_litgpt.py --model_name Llama-3-70B  --n_layers 2 --compile thunder --checkpoint_activations True`

### Additional context

Note this bug is similar to #1013 and can be fixed by #1067.

Stack trace:

```shell
Traceback (most recent call last):
  File "/opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 881, in <module>
    CLI(benchmark_main)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 204, in _run_component
    return component(**cfg)
  File "/opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 795, in benchmark_main
    benchmark.train()
  File "/opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 697, in train
    logits = self.model(input_ids)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/pytorch/lightning-thunder/thunder/core/module.py", line 80, in forward
    res = self._forward_fn(*args, **kwargs)
  File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 717, in fn_
    cache_entry, inps, pro_to_epi = get_computation_and_inputs(*args, **kwargs)
  File "/opt/pytorch/lightning-thunder/thunder/core/langctxs.py", line 136, in _fn
    result = fn(*args, **kwargs)
  File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 219, in cache_info_wrapper
    res = fn(*args, **kwargs)
  File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 630, in get_computation_and_inputs
    computation_trc, backward_trc = split_forward_backward(computation_trc, cd, cs, *inps)
  File "/opt/pytorch/lightning-thunder/thunder/executors/torch_autograd.py", line 237, in split_forward_backward
    fw_extrace, bw_extrace = rematerialize_forward_and_backward(fw_extrace, bw_extrace)
  File "/opt/pytorch/lightning-thunder/thunder/core/rematerialization.py", line 610, in rematerialize_forward_and_backward
    joint_extrace = rematerialize(joint_extrace)
  File "/opt/pytorch/lightning-thunder/thunder/core/rematerialization.py", line 559, in rematerialize
    updated_consumer = apply_rematerialization_for_consumer(current_producer, current_consumer, cut)
  File "/opt/pytorch/lightning-thunder/thunder/core/rematerialization.py", line 193, in apply_rematerialization_for_consumer
    new_consumer_args = tuple(sorted(new_consumer_args, key=lambda x: proxy_order[x.name]))
  File "/opt/pytorch/lightning-thunder/thunder/core/rematerialization.py", line 193, in <lambda>
    new_consumer_args = tuple(sorted(new_consumer_args, key=lambda x: proxy_order[x.name]))
KeyError: 'attention_output'
```

**Comment by t-vi** [comment]
A quick update from me: I tried to look into finding the root cause. One item that seem very problematic is the creation of the joint trace, which will lead to duplicate names in the joint trace. I'm trying to fix that in this branch:

https://github.com/Lightning-AI/lightning-thunder/tree/tom/wip-remat-key-error

It is, however not a full solution. :(
