### ISSUE TITLE
improve stack traces in the Thunder Python Interpreter with context managers

### ISSUE THREAD

**Issue by t-vi** [Lightning-AI/lightning-thunder#1223]
We currently do not seem to preserve the traceback when we have context manager `__exit__` cleanups, we should.
We should probably also remove all purely interpreter-internal stack frames that sit below the outermost user one. 

Example: I wanted to debug NeVA and had this stack trace from Thunder (nemo.sh in @tfogal 's NeVA testing)
```
[....omitted a lot...]
[rank0]:   File "/teamspace/studios/this_studio/nemo/nemo/collections/nlp/modules/common/megatron/language_model.py", line 829, in forward
[rank0]:     encoder_output = self.encoder(
[rank0]:   File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/thunder/core/interpreter.py", line 6466, in _impl
[rank0]:     return fn.__func__(fn.__self__, *args, **kwargs)
[rank0]:   File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/thunder/core/interpreter.py", line 6466, in _impl
[rank0]:     return fn.__func__(fn.__self__, *args, **kwargs)
[rank0]:   File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/thunder/core/interpreter.py", line 6466, in _impl
[rank0]:     return fn.__func__(fn.__self__, *args, **kwargs)
[rank0]:   File "/teamspace/studios/this_studio/nemo/nemo/collections/nlp/modules/common/megatron/transformer.py", line 1635, in forward
[rank0]:     hidden_states = layer(
[rank0]: TypeError: forward(): incompatible function arguments. The following argument types are supported:
[rank0]:     1. (arg0: torch.Tensor, arg1: float) -> torch.Tensor

[rank0]: Invoked with: <TensorProxy(name="t4334", dtype=thunder.dtypes.bfloat16, shape=(80, 384, 384))>, <TensorProxy(name="t4338", dtype=thunder.dtypes.int64, shape=())>
```

Now there is some crucial information missing between `layer` and `forward`, but all the impls that lead to the `hidden_state = layer(` call are uninformative.

I first complemented the torch opaque function calling error in jit_ext.general_jit_lookaside with a version printing also on other opaque functions being called with tensorproxies. There are a few false positives (something `__new__`, `__setitem__` etc.) / not of immediate interest, but then I got:
```
[NeMo W 2024-09-30 21:00:38 nemo_logging:349] /home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/thunder/core/jit_ext.py:952: UserWarning: Trying to call function <built-in method forward of PyCapsule object at 0x7f2c0c413a50> getattr(fn, "__self__", None)=<capsule object NULL at 0x7f2c0c413a50> getattr(fn, "__qualname__", None)='PyCapsule.forward'  but it is not yet supported. 
      warnings.warn(calling_opaque_msg)
```
huh. PyCapsule and NULL is not that informative.

Adding `traceback.print_exception` and printing `runtimectx.frame_stack` infos (it's terribly formatted, I should print `module.qualname` and the filename along with positions) .
Note how we see the error twice, once where it happens with the interesting traceback including `apex.transformer.functional.fused_softmax.ScaledUpperTriangMaskedSoftmax.forward ` being the `pycapsule.forward` we were looking for, and the other (the one that leads to above traceback) is a lot less interesting and from the context manager cleanup, apparently.
 
```
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/thunder/core/interpreter.py", line 6594, in _call_dispatch
    opaque_result: Any = fn(*args_, **kwargs_)
TypeError: forward(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: float) -> torch.Tensor

Invoked with: <TensorProxy(name="t4334", dtype=thunder.dtypes.bfloat16, shape=(80, 384, 384))>, <TensorProxy(name="t4338", dtype=thunder.dtypes.int64, shape=())>
interpret.<locals>.fn_.<locals>.getfn.<locals>.fn_2 thunder.core.interpreter Positions(lineno=7155, end_lineno=7155, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Float16Module.forward nemo.collections.nlp.modules.common.megatron.module Positions(lineno=292, end_lineno=292, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
NevaModel.forward nemo.collections.multimodal.models.multimodal_llm.neva.neva_model Positions(lineno=475, end_lineno=475, col_offset=0, end_col_offset=999)
GPTModel.forward nemo.collections.nlp.models.language_modeling.megatron.gpt_model Positions(lineno=286, end_lineno=286, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
TransformerLanguageModel.forward nemo.collections.nlp.modules.common.megatron.language_model Positions(lineno=829, end_lineno=829, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
ParallelTransformer.forward nemo.collections.nlp.modules.common.megatron.transformer Positions(lineno=1635, end_lineno=1635, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
ParallelTransformerLayer.forward nemo.collections.nlp.modules.common.megatron.transformer Positions(lineno=757, end_lineno=757, col_offset=0, end_col_offset=999)
ParallelTransformerLayer_.forward nemo.collections.nlp.modules.common.megatron.transformer Positions(lineno=506, end_lineno=506, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
ParallelAttention.forward nemo.collections.nlp.modules.common.megatron.attention Positions(lineno=554, end_lineno=554, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
CoreAttention.forward nemo.collections.nlp.modules.common.megatron.attention Positions(lineno=911, end_lineno=911, col_offset=0, end_col_offset=999)
CoreAttention.torch_attention nemo.collections.nlp.modules.common.megatron.attention Positions(lineno=965, end_lineno=965, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
FusedScaleMaskSoftmax.forward apex.transformer.functional.fused_softmax Positions(lineno=218, end_lineno=218, col_offset=0, end_col_offset=999)
FusedScaleMaskSoftmax.forward_fused_softmax apex.transformer.functional.fused_softmax Positions(lineno=251, end_lineno=251, col_offset=0, end_col_offset=999)
scaled_upper_triang_masked_softmax apex.transformer.functional.fused_softmax Positions(lineno=60, end_lineno=60, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
ScaledUpperTriangMaskedSoftmax.forward apex.transformer.functional.fused_softmax Positions(lineno=34, end_lineno=34, col_offset=0, end_col_offset=999)
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/thunder/core/interpreter.py", line 6594, in _call_dispatch
    opaque_result: Any = fn(*args_, **kwargs_)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/thunder/core/interpreter.py", line 6284, in thunder_interpreter_generator
    send_value = yield unwrap(res)
TypeError: forward(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: float) -> torch.Tensor

Invoked with: <TensorProxy(name="t4334", dtype=thunder.dtypes.bfloat16, shape=(80, 384, 384))>, <TensorProxy(name="t4338", dtype=thunder.dtypes.int64, shape=())>
interpret.<locals>.fn_.<locals>.getfn.<locals>.fn_2 thunder.core.interpreter Positions(lineno=7155, end_lineno=7155, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Float16Module.forward nemo.collections.nlp.modules.common.megatron.module Positions(lineno=292, end_lineno=292, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
NevaModel.forward nemo.collections.multimodal.models.multimodal_llm.neva.neva_model Positions(lineno=475, end_lineno=475, col_offset=0, end_col_offset=999)
GPTModel.forward nemo.collections.nlp.models.language_modeling.megatron.gpt_model Positions(lineno=286, end_lineno=286, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
TransformerLanguageModel.forward nemo.collections.nlp.modules.common.megatron.language_model Positions(lineno=829, end_lineno=829, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._wrapped_call_impl torch.nn.modules.module Positions(lineno=1553, end_lineno=1553, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
Module._call_impl torch.nn.modules.module Positions(lineno=1562, end_lineno=1562, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
ParallelTransformer.forward nemo.collections.nlp.modules.common.megatron.transformer Positions(lineno=1635, end_lineno=1635, col_offset=0, end_col_offset=999)
_call_dispatch.<locals>._impl thunder.core.interpreter Positions(lineno=6466, end_lineno=6466, col_offset=0, end_col_offset=999)
_GeneratorContextManager.__exit__ contextlib Positions(lineno=153, end_lineno=153, col_offset=0, end_col_offset=999)
thunder_graphs=0 / num_graphs=0
Error executing job with overrides: ['trainer.precision=bf16-mixed', 'model.megatron_amp_O2=True', 'model.mcore_gpt=False', 'trainer.num_nodes=1', 'trainer.devices=1', 'trainer.val_check_interval=10', 'trainer.limit_val_batches=5', 'trainer.log_every_n_steps=1', '++exp_manager.max_time_per_run=00:00:03:00', 'trainer.max_steps=20', 'model.micro_batch_size=2', 'model.global_batch_size=4', 'model.tensor_model_parallel_size=1', 'model.pipeline_model_parallel_size=1', 'exp_manager.create_checkpoint_callback=False', 'model.data.data_path=./data/multimodal/tiny-neva/dummy.json', 'model.data.image_folder=./data/multimodal/tiny-neva/images', 'model.tokenizer.library=sentencepiece', 'model.tokenizer.model=./data/multimodal/tiny-neva/tokenizer_add_special.model', 'model.num_layers=2', 'model.hidden_size=5120', 'model.ffn_hidden_size=13824', 'model.num_attention_heads=40', 'model.normalization=rmsnorm', 'model.data.num_workers=0', 'model.data.conv_template=llama_2', 'model.mm_cfg.vision_encoder.from_pretrained=openai/clip-vit-large-patch14', 'model.mm_cfg.llm.from_pretrained=null', 'model.use_flash_attention=false', 'exp_manager.exp_dir=./foo-neva-train']
```

cc @lantiga @borda @carmocca

**Comment by t-vi** [comment]
Also with `finally` (the verbosity, but crucially note that the frame inside "bar" is missing).

```python
import thunder, traceback
def bar():
    print('A' * 'A')
def fn():
    try:
        bar()
    finally:
        pass

import traceback
jfn = thunder.jit(fn)
print("####python###")
try:
    fn()
except Exception as e:
    print('\n'.join(traceback.format_tb(e.__traceback__)))
print("####thunder###")
try:
    jfn()
except Exception as e:
    print('\n'.join(traceback.format_tb(e.__traceback__)))
```

```python
####python###
  File "/tmp/ipykernel_37089/702456467.py", line 14, in <module>
    fn()

  File "/tmp/ipykernel_37089/702456467.py", line 6, in fn
    bar()

  File "/tmp/ipykernel_37089/702456467.py", line 3, in bar
    print('A' * 'A')

####thunder###
  File "/tmp/ipykernel_37089/702456467.py", line 19, in <module>
    jfn()

  File "/teamspace/studios/this_studio/lightning-thunder/thunder/__init__.py", line 815, in wrapped
    return fn(*args, **kwargs)

  File "/teamspace/studios/this_studio/lightning-thunder/thunder/__init__.py", line 855, in fn_
    cache_entry, inps, pro_to_epi = get_computation_and_inputs(*args, **kwargs)

  File "/teamspace/studios/this_studio/lightning-thunder/thunder/__init__.py", line 794, in wrapped
    cache_entry, inps, pro_to_epi = get_computation_and_inputs_fn(*args, **kwargs)

  File "/teamspace/studios/this_studio/lightning-thunder/thunder/core/langctxs.py", line 136, in _fn
    result = fn(*args, **kwargs)

  File "/teamspace/studios/this_studio/lightning-thunder/thunder/__init__.py", line 236, in cache_info_wrapper
    res = fn(*args, **kwargs)

  File "/teamspace/studios/this_studio/lightning-thunder/thunder/__init__.py", line 759, in get_computation_and_inputs
    prologue_trc, computation_trc, epilogue_trc = acquire_initial_trace(fn, args, kwargs, cd, cs, ad_hoc_executor)

  File "/teamspace/studios/this_studio/lightning-thunder/thunder/__init__.py", line 438, in acquire_initial_trace
    jit_results: TraceResults = thunder_general_jit(

  File "/teamspace/studios/this_studio/lightning-thunder/thunder/core/jit_ext.py", line 2133, in thunder_general_jit
    result = jfn(*args, **kwargs)

  File "/teamspace/studios/this_studio/lightning-thunder/thunder/core/interpreter.py", line 7567, in fn_
    raise e

  File "/teamspace/studios/this_studio/lightning-thunder/thunder/core/interpreter.py", line 7526, in fn_2
    return fn(*args, **kwargs)

  File "/tmp/ipykernel_37089/702456467.py", line 6, in fn
    bar()
```
