### ISSUE TITLE
NotImplementedError: torch.where() does not support only specifying a condition

### ISSUE THREAD

**Issue by wprazuch** [Lightning-AI/lightning-thunder#1297]
When running Mixtral-8x7B-v0.1 with Thunder we get an error:
```
NotImplementedError: torch.where() does not support only specifying a condition
```

## 🐛 Bug

Full traceback:
```
22: Exception: Unexpected error occurred for {'--micro_batch_size': 1} due to [rank22]: Traceback (most recent call last):
22: [rank22]:   File "/workspace/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 949, in <module>
22: [rank22]:     CLI(benchmark_main)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 96, in CLI
22: [rank22]:     return _run_component(components, init)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 204, in _run_component
22: [rank22]:     return component(**cfg)
22: [rank22]:   File "/workspace/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 861, in benchmark_main
22: [rank22]:     benchmark.train()
22: [rank22]:   File "/workspace/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 742, in train
22: [rank22]:     logits = self.model(input_ids)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
22: [rank22]:     return self._call_impl(*args, **kwargs)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
22: [rank22]:     return forward_call(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/module.py", line 80, in forward
22: [rank22]:     res = self._forward_fn(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 737, in fn_
22: [rank22]:     cache_entry, inps, pro_to_epi = get_computation_and_inputs(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/langctxs.py", line 136, in _fn
22: [rank22]:     result = fn(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 232, in cache_info_wrapper
22: [rank22]:     res = fn(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 521, in get_computation_and_inputs
22: [rank22]:     jit_results: TraceResults = thunder_general_jit(
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/jit_ext.py", line 1698, in thunder_general_jit
22: [rank22]:     result = jfn(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 7190, in fn_
22: [rank22]:     raise e
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 7151, in fn_2
22: [rank22]:     return fn(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6466, in _impl
22: [rank22]:     return fn.__func__(fn.__self__, *args, **kwargs)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
22: [rank22]:     return self._call_impl(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6466, in _impl
22: [rank22]:     return fn.__func__(fn.__self__, *args, **kwargs)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
22: [rank22]:     return forward_call(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6466, in _impl
22: [rank22]:     return fn.__func__(fn.__self__, *args, **kwargs)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/litgpt/model.py", line 94, in forward
22: [rank22]:     x = block(x, cos, sin, mask, input_pos)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6466, in _impl
22: [rank22]:     return fn.__func__(fn.__self__, *args, **kwargs)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
22: [rank22]:     return self._call_impl(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6466, in _impl
22: [rank22]:     return fn.__func__(fn.__self__, *args, **kwargs)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
22: [rank22]:     return forward_call(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6466, in _impl
22: [rank22]:     return fn.__func__(fn.__self__, *args, **kwargs)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/litgpt/model.py", line 205, in forward
22: [rank22]:     x = self.post_mlp_norm(self.mlp(self.norm_2(x))) + x
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6466, in _impl
22: [rank22]:     return fn.__func__(fn.__self__, *args, **kwargs)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
22: [rank22]:     return self._call_impl(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6466, in _impl
22: [rank22]:     return fn.__func__(fn.__self__, *args, **kwargs)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
22: [rank22]:     return forward_call(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6466, in _impl
22: [rank22]:     return fn.__func__(fn.__self__, *args, **kwargs)
22: [rank22]:   File "/usr/local/lib/python3.10/dist-packages/litgpt/model.py", line 402, in forward
22: [rank22]:     token_idx, expert_idx = torch.where(mask)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 1292, in wrapping_wrapper
22: [rank22]:     res = ufn(*uargs, **ukwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/jit_ext.py", line 392, in wrapper
22: [rank22]:     return fn(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/symbol.py", line 320, in __call__
22: [rank22]:     result = self.meta(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/langctxs.py", line 136, in _fn
22: [rank22]:     result = fn(*args, **kwargs)
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/torch/__init__.py", line 2342, in where
22: [rank22]:     utils.check(
22: [rank22]:   File "/opt/pytorch/lightning-thunder/thunder/core/baseutils.py", line 107, in check
22: [rank22]:     raise exception_type(s())
22: [rank22]: NotImplementedError: torch.where() does not support only specifying a condition
```

### To Reproduce

Please use:
8 node(s), each with 8 GPUs.
Image ""INTERNAL_IMAGE:pjnl-20241011""
Training script:
python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py \
    --model_name Mixtral-8x7B-v0.1 \
    --distributed_mode fsdp \
    --shard_mode zero3 \
    --compile thunder \
    --checkpoint_activations True \
    --low_precision_mode none  \
    --micro_batch_size 1

### Expected behavior

We should not see this error.

### Environment

system.device_product_name                      DGXH100
system.gpu_driver_version                    535.129.03
libraries.cuda                               12.6.2.004
libraries.pip.lightning               2.4.0.dev20240728
libraries.pip.lightning-thunder              0.2.0.dev0
libraries.pip.lightning-utilities                0.11.7
libraries.pip.litgpt                             0.4.11
libraries.pip.nvfuser                 0.2.15+gitf3a2087
libraries.pip.pytorch-lightning                   2.4.0
libraries.pip.torch                  2.6.0a0+git4e89977
libraries.pip.torchmetrics                        1.4.3
libraries.pip.torchvision              0.19.0a0+d23a6e1"

**Comment by wprazuch** [comment]
Closing as duplicate
