### ISSUE TITLE
NotImplementedError: VJP for PrimIDs.ITEM is not implemented for ThunderFX and litgGPT models.

### ISSUE THREAD

**Issue by mpatel31415** [Lightning-AI/lightning-thunder#1479]
## 🐛 Bug

For Llama-3-8B, Mistral-7B-v0.1 and Phi-3-mini-4k-instruct we get the following error:

> 6: [rank6]: Traceback (most recent call last):
6: [rank6]:   File "/workspace/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 980, in <module>
6: [rank6]:     CLI(benchmark_main)
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/jsonargparse/_cli.py", line 96, in CLI
6: [rank6]:     return _run_component(components, init)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/jsonargparse/_cli.py", line 204, in _run_component
6: [rank6]:     return component(**cfg)
6: [rank6]:            ^^^^^^^^^^^^^^^^
6: [rank6]:   File "/workspace/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 877, in benchmark_main
6: [rank6]:     benchmark.train()
6: [rank6]:   File "/workspace/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 748, in train
6: [rank6]:     logits = self.model(input_ids)
6: [rank6]:              ^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
6: [rank6]:     return self._call_impl(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
6: [rank6]:     return forward_call(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py", line 573, in _fn
6: [rank6]:     return fn(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/_dynamo/external_utils.py", line 31, in inner
6: [rank6]:     return fn(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
6: [rank6]:     return self._call_impl(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
6: [rank6]:     return forward_call(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 864, in forward
6: [rank6]:     output = self._fsdp_wrapped_module(*args, **kwargs)
6: [rank6]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
6: [rank6]:     return self._call_impl(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
6: [rank6]:     return forward_call(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/litgpt/model.py", line 94, in forward
6: [rank6]:     x = block(x, cos, sin, mask, input_pos)
6: [rank6]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
6: [rank6]:     return self._call_impl(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
6: [rank6]:     return forward_call(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 864, in forward
6: [rank6]:     output = self._fsdp_wrapped_module(*args, **kwargs)
6: [rank6]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
6: [rank6]:     return self._call_impl(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
6: [rank6]:     return forward_call(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/litgpt/model.py", line 167, in forward
6: [rank6]:     def forward(
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
6: [rank6]:     return self._call_impl(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
6: [rank6]:     return forward_call(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py", line 744, in _fn
6: [rank6]:     return fn(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/fx/graph_module.py", line 822, in call_wrapped
6: [rank6]:     return self._wrapped_call(self, *args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/fx/graph_module.py", line 400, in __call__
6: [rank6]:     raise e
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/fx/graph_module.py", line 387, in __call__
6: [rank6]:     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
6: [rank6]:     return self._call_impl(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
6: [rank6]:     return forward_call(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "<eval_with_key>.14", line 5, in forward
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
6: [rank6]:     return self._call_impl(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
6: [rank6]:     return forward_call(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/core/module.py", line 80, in forward
6: [rank6]:     res = self._forward_fn(*args, **kwargs)
6: [rank6]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 774, in wrapped
6: [rank6]:     return fn(*args, **kwargs)
6: [rank6]:            ^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 824, in fn_
6: [rank6]:     cache_entry, inps, pro_to_epi = get_computation_and_inputs(*args, **kwargs)
6: [rank6]:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 756, in wrapped
6: [rank6]:     cache_entry, inps, pro_to_epi = get_computation_and_inputs_fn(*args, **kwargs)
6: [rank6]:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/core/langctxs.py", line 136, in _fn
6: [rank6]:     result = fn(*args, **kwargs)
6: [rank6]:              ^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 236, in cache_info_wrapper
6: [rank6]:     res = fn(*args, **kwargs)
6: [rank6]:           ^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 659, in get_computation_and_inputs
6: [rank6]:     computation_trc, backward_trc = split_forward_backward(computation_trc, cd, cs, *inps)
6: [rank6]:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/executors/torch_autograd.py", line 156, in split_forward_backward
6: [rank6]:     fw_trace, bw_trace = forward_and_backward_from_trace(primal_trace, torch_autograd=True)
6: [rank6]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/core/transforms.py", line 3016, in forward_and_backward_from_trace
6: [rank6]:     forward_trace, result, env = augmented_forward_pass_trace(trace, *trace.args, **trace.kwargs)
6: [rank6]:                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/core/transforms.py", line 2632, in augmented_forward_pass_trace
6: [rank6]:     trace, result, env = interpret_trace_to_trace(
6: [rank6]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/core/trace_interpreter.py", line 168, in interpret_trace_to_trace
6: [rank6]:     result = prim_func(*args, **kwargs)
6: [rank6]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/core/transforms.py", line [254](https://gitlab-master.nvidia.com/dl/jet/ci/-/jobs/124481348#L254)5, in _vjp_impl
6: [rank6]:     out_primal, out_residuals = vjp_impl(*primals, **kwargs)
6: [rank6]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/core/transforms.py", line 2319, in decomposed_fn_aug_fwd_rule
6: [rank6]:     result, env = augmented_forward_pass(*args, trace=trace, **kwargs)
6: [rank6]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/core/transforms.py", line [260](https://gitlab-master.nvidia.com/dl/jet/ci/-/jobs/124481348#L260)4, in augmented_forward_pass
6: [rank6]:     result, env = eval_trace(
6: [rank6]:                   ^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/core/trace_interpreter.py", line 63, in interpret_trace
6: [rank6]:     prim_func = symbol_mapper(symbol) if symbol_mapper is not None else symbol.sym
6: [rank6]:                 ^^^^^^^^^^^^^^^^^^^^^
6: [rank6]:   File "/opt/pytorch/lightning-thunder/thunder/core/transforms.py", line 2541, in vjp_symbol_mapper
6: [rank6]:     raise NotImplementedError(f"VJP for {symbol.sym.id} is not implemented")
6: [rank6]: NotImplementedError: VJP for PrimIDs.ITEM is not implemented

### To Reproduce

Please use:
1 GPU (H100)
Image "INTERNAL_IMAGE:pjnl-20241125"
Training script:

```
python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py
--model_name  Mistral-7B-v0.1 
--compile dynamo_thunder
--micro_batch_size 1
```

### Environment

As in the pjnl image

cc @tfogal

**Comment by mpatel31415** [comment]
Just to let you know - this issue was discovered in canary runs of LitGPT models, I'm not sure if it's related to nemo, as the label suggest.
