### ISSUE TITLE
In #1415 networkx seems to fail to complete min cut

### ISSUE THREAD

**Issue by crcrpar** [Lightning-AI/lightning-thunder#1567]
#1415 

## 🐛 Bug

networkx seems to fail to complete min cut for an MLP with two torchao.float8 linears and GELU, bf16.
The script below works when dtype is float32.

```
Traceback (most recent call last):
  File "/opt/pytorch/lightning-thunder/thunder/core/rematerialization.py", line 378, in find_cut
    _, (reachable, non_reachable) = nx.minimum_cut(g, "source", "sink")
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<class 'networkx.utils.decorators.argmap'> compilation 4", line 3, in argmap_minimum_cut_1
  File "/usr/local/lib/python3.12/dist-packages/networkx/utils/backends.py", line 967, in __call__
    return self.orig_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/networkx/algorithms/flow/maxflow.py", line 454, in minimum_cut
    R = flow_func(flowG, _s, _t, capacity=capacity, value_only=True, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<class 'networkx.utils.decorators.argmap'> compilation 8", line 3, in argmap_preflow_push_5
  File "/usr/local/lib/python3.12/dist-packages/networkx/utils/backends.py", line 967, in __call__
    return self.orig_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/networkx/algorithms/flow/preflowpush.py", line 422, in preflow_push
    R = preflow_push_impl(G, s, t, capacity, residual, global_relabel_freq, value_only)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/networkx/algorithms/flow/preflowpush.py", line 41, in preflow_push_impl
    detect_unboundedness(R, s, t)
  File "<class 'networkx.utils.decorators.argmap'> compilation 16", line 3, in argmap_detect_unboundedness_13
  File "/usr/local/lib/python3.12/dist-packages/networkx/utils/backends.py", line 967, in __call__
    return self.orig_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/networkx/algorithms/flow/utils.py", line 173, in detect_unboundedness
    raise nx.NetworkXUnbounded(
networkx.exception.NetworkXUnbounded: Infinite capacity path, flow unbounded above.
```

### To Reproduce

- Checkout #1415, more specifically, 0893fbeb2a11c8df564b2c517f114212451b9417.

#### Code sample
```python
import torch
import torch.nn as nn
from torchao.float8 import convert_to_float8_training
import thunder
from thunder.tests.make_tensor import make_tensor


def main():
    batch_size, in_features, out_features = 16, 32, 64

    device = torch.device("cuda")
    dtype = torch.bfloat16
    bias = True

    model = nn.Sequential(
        nn.Linear(in_features, out_features, bias=bias),
        nn.GELU(approximate="tanh"),
        nn.Linear(out_features, out_features, bias=bias),
    ).to(device=device, dtype=dtype)
    fp8_model = convert_to_float8_training(model)
    x = make_tensor((batch_size, in_features), device=device, dtype=dtype)

    jitted = thunder.jit(fp8_model, executors=[thunder.get_executor("torch"), thunder.get_executor("nvfuser")])
    actual = jitted(x)


if __name__ == "__main__":
    main()
```

### Environment

- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by IvanYashchuk** [comment]
We used to hit the same error with Thunder recomputation enabled (https://github.com/Lightning-AI/lightning-thunder/issues/1232). @riccardofelluga, since you hit this problem before do you have a minimal reproducer for the problem? Do you know what changes are needed in the trace here?

**Comment by riccardofelluga** [comment]
Min-cut issues are not easy to nail down, tho I've observed that sometimes it might arise from duplicates in the trace. Is this error still relevant? I am not able to reproduce with the given snippet and checked out at `subclass_tensor-type-str`

**Comment by IvanYashchuk** [comment]
@riccardofelluga, have you looked into that?

**Comment by riccardofelluga** [comment]
I haven't yet, this fell through in the priorities :( can reprioritize it and check it out this week

**Comment by riccardofelluga** [comment]
While the repro script does not reproduce the issue, the min-cut problem is still there for the tests. From a first investigation what it seems to happen is that the one of the inputs to the consumer is not present in the graph, i.e. for the following producer consumer pair:
```python
# Producer
[t398, t400, t423, t408, t427, s, t456, t528] = nvFusion1(t110)
# Consumer
[t426, t555, t728, t684] = nvFusion2(t648, t629, t408, t423, t516, t398, t400)
```
the producer does not create t648 which is instead result form the following and it is not included as external dependency when constructing the graph. 

```python
t648 = torch._scaled_mm(t640, t716, t627, t647, None, None, torch.bfloat16, False)  # t648: "cuda:0 bf16[64, 64]"
```
