### ISSUE TITLE
Fusion pass should drop unused arg from parent symbols.

### ISSUE THREAD

**Issue by jjsjann123** [Lightning-AI/lightning-thunder#531]
## 🐛 Bug

In the trace below, `ab` is a tuple of slices `(slice(3, 1), slice(1, 2))`. Currently the problem is that, during fusion pass, we make the fusion decision by looking at the nested operation `prim.slice_prim` to check if we should accept or reject the operation.

```
@torch.no_grad()
@no_autocast
def computation(t, ab):
  # t: "cuda:0 f32[5, 3]"
  # ab: "tuple"
  t0 = Tensor.__getitem__(t, ab)  # t0: "cuda:0 f32[0, 1]"
    # t0 = ltorch.getitem(t, ab)  # t0: "cuda:0 f32[0, 1]"
      # t0 = prims.slice_prim(t, [0, 1], [0, 2], [1, 1])  # t0: "cuda:0 f32[0, 1]"
  del t, ab
  return t0]
```

When we choose to fuse the `slice_prim` op, we ended up with a fusion IR like
```
@torch.no_grad()
@no_autocast
def computation(a, b):
  # t: "cuda:0 f32[5, 3]"
  # ab: "tuple"
  [t0] = nvFusion0(t, ab)
    # t0 = prims.slice_prim(t, [0, 1], [0, 2], [1, 1])  # t0: "cuda:0 f32[0, 1]"
  return t0,
```

This gives us complexity in addressing `ab` as part of the cache entry, as well as mapping `ab` to fusion inputs. We need to drop it and instead getting fusion symbol as `[t0] = nvFusion0(t)`.

### To Reproduce

```
import torch
import thunder
import operator

def foo(t, ab):
    return operator.getitem(t, ab)

# enable bookend would remove the error and let you look at the trace without fusion.
jfoo = thunder.functional.jit(foo, interpretation="python interpreter", cache="no caching", disable_torch_autograd=True, nv_enable_bookend=False)

dtype = torch.float32
t = torch.randn(5, 3, device="cuda").to(dtype=dtype)

ab = (slice(3, 1), slice(1, 2))

out = jfoo(t, ab)
out_ref = foo(t, ab)
print("\t===== prologue trace =====\n", jfoo._lc_cs.last_prologue_traces[-1])
print("\t===== compute trace =====\n", jfoo._lc_cs.last_traces)
assert(out.equal(out_ref))
```

The error below should be gone.
```
Traceback (most recent call last):
  File "/volume/thunder_517.py", line 15, in <module>
    out = jfoo(t, ab)
  File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 644, in fn_
    result = cache_entry.computation_fn(*inps)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 42, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 42, in decorate_autocast
    return func(*args, **kwargs)
  File "thunder.computation_1", line 10, in computation
  File "/opt/pytorch/lightning-thunder/thunder/executors/nvfuserex_impl.py", line 402, in __call__
    fd = self.get_fd(to_descriptors(args))
  File "/opt/pytorch/lightning-thunder/thunder/executors/nvfuserex_impl.py", line 385, in to_descriptors
    return tuple(to_descriptor(arg) for arg in args)
  File "/opt/pytorch/lightning-thunder/thunder/executors/nvfuserex_impl.py", line 385, in <genexpr>
    return tuple(to_descriptor(arg) for arg in args)
  File "/opt/pytorch/lightning-thunder/thunder/executors/nvfuserex_impl.py", line 373, in to_descriptor
    numbertype, _ = check_same_dtype(*arg)
  File "/opt/pytorch/lightning-thunder/thunder/core/utils.py", line 220, in check_same_dtype
    typ = to_dtype(a, true_dtype=True)
  File "/opt/pytorch/lightning-thunder/thunder/core/dtypes.py", line 330, in to_dtype
    raise ValueError(f"Trying to extract a dtype from object {x} with unknown type {type(x)}!")
ValueError: Trying to extract a dtype from object slice(3, 4, None) with unknown type <class 'slice'>!
```

**Comment by jjsjann123** [comment]
This would fix the nvfuser issue reported in #482, but it's only part of the problem.
