### ISSUE TITLE
unhashable type: 'TensorProxy' error on NeVA model

### ISSUE THREAD

**Issue by tfogal** [Lightning-AI/lightning-thunder#601]
While trying to `thunder.jit` portions of the NeMo's NeVA model, I found this `unhashable type` error. Attached is [a simplified / reduced example that requires NeMo](https://github.com/user-attachments/files/15844230/unhashable-type.py.txt).

The full traceback is:
```python
Traceback (most recent call last):
  File "$HOME/dev/nemo/repro/unhashable-type.py", line 64, in <module>
    x = fwd(input_ids)
  File "$HOME/dev/thunder/thunder/__init__.py", line 659, in fn_
    cache_entry, inps, pro_to_epi = get_computation_and_inputs(*args, **kwargs)
  File "$HOME/dev/thunder/thunder/__init__.py", line 217, in cache_info_wrapper
    res = fn(*args, **kwargs)
  File "$HOME/dev/thunder/thunder/__init__.py", line 496, in get_computation_and_inputs
    jit_results: TraceResults = interpreter(
  File "$HOME/dev/thunder/thunder/__init__.py", line 205, in _general_frontend
    return thunder_general_jit(fn, args, kwargs, sharp_edges=sharp_edges, record_history=record_history)
  File "$HOME/dev/thunder/thunder/core/jit_ext.py", line 1605, in thunder_general_jit
    result = jfn(*args, **kwargs)
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 6696, in fn_
    raise e
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 6664, in fn_2
    return fn(*args, **kwargs)
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 6061, in _impl
    return fn.__func__(fn.__self__, *args, **kwargs)
  File "$HOME/dev/nemo/nemo/collections/multimodal/models/multimodal_llm/neva/neva_model.py", line 168, in forward
    return self.replace_media_embeddings(input_ids, words_embeddings, media)
  File "$HOME/dev/nemo/nemo/collections/multimodal/models/multimodal_llm/neva/neva_model.py", line 216, in replace_media_embeddings
    media_features = self.encode_vision_x(media)  # b T F S(eq) H(idden)
  File "$HOME/dev/nemo/nemo/collections/multimodal/models/multimodal_llm/neva/neva_model.py", line 194, in encode_vision_x
    vision_x = vision_x.to(self.vision_encoder.dtype)
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 1539, in <lambda>
    return lambda _, obj, __: method(obj)
  File "$HOME/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 976, in dtype
    return get_parameter_dtype(self)
  File "$HOME/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 245, in get_parameter_dtype
    for t in parameter.parameters():
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 4060, in _next_impl
    return next(tos)
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 1863, in impl
    return iterator.__next__()
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 6189, in _call_dispatch
    opaque_result: Any = fn(*args_, **kwargs_)
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 5895, in thunder_interpreter_generator
    raise e
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2255, in parameters
    for name, param in self.named_parameters(recurse=recurse):
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 4060, in _next_impl
    return next(tos)
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 1863, in impl
    return iterator.__next__()
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 6189, in _call_dispatch
    opaque_result: Any = fn(*args_, **kwargs_)
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 5895, in thunder_interpreter_generator
    raise e
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2288, in named_parameters
    yield from gen
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 5835, in impl
    return generator.__next__()
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 6189, in _call_dispatch
    opaque_result: Any = fn(*args_, **kwargs_)
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 5895, in thunder_interpreter_generator
    raise e
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2226, in _named_members
    if v is None or v in memo:
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 3684, in impl
    return getattr(tos, "__contains__")(tos1)
  File "$HOME/dev/thunder/thunder/core/interpreter.py", line 6189, in _call_dispatch
    opaque_result: Any = fn(*args_, **kwargs_)
TypeError: unhashable type: 'TensorProxy'
```

To reproduce you may want specific versions of dependencies:
```
transformers==4.40.2
git+ssh://git@github.com/NVIDIA/NeMo.git@f073ed9cb262620d4866041645ba91aee72003c8#egg=nemo_toolkit
pytorch-lightning==2.2.5
```
and torch nightly

cc @apaz-cli @tfogal

**Comment by mruberry** [comment]
triage review:

- we probably need an implementation for torch.Tensor.__hash__
- we may need a follow-up issue with the jit and collections

**Comment by t-vi** [comment]
There are several tricky bits wrt this:
- how to do the cache invalidation vs. aliasing, so we could record and use the id's of passed in tensors as the hash of tensor proxies,
- the next thing will have programs add things to collections and then we're leaking tensor proxies if the collection has not been temporary (probably not the case here.

There will be more tricky bits.

Note that this instance is actually from PyTorch's own `Module._named_members` impl (so a temporary collection),  so we might also sidestep the issue by diverting PyTorch's Module member functions appropriately (on the other hand, modules calling .parameters() or so seems to be decidedly non-obscure, `my_device = next(self.parameters()).device` has been a thing for a long time.
