### ISSUE TITLE
Fail to interpret `megatron.core.tensor_parallel.layers.LinearWithGradAccumulationAndAsyncCommunication`

### ISSUE THREAD

**Issue by crcrpar** [Lightning-AI/lightning-thunder#694]
*Note*: If you have a model or program that is not supported yet but should be, please use the program coverage template.

#### Code sample

```python
import torch
from nemo.collections.nlp.modules.common.megatron.mlp import ParallelMLP
from megatron.core.tensor_parallel.layers import LinearWithGradAccumulationAndAsyncCommunication

import thunder


def f(x: torch.Tensor, weight: torch.Tensor, bias: torch.Tensor) -> tuple[torch.Tensor]:
    return LinearWithGradAccumulationAndAsyncCommunication.apply(
        x,
        weight,
        bias,
        False,  # gradient_accumulation_fusion
        False,  # allreduce_dgrad
        False,  # sequence_parallel
        None,  # grad_output_buffer
    )


def main():
    device = torch.device("cuda")
    s, b, hp = 1025, 1, 256
    with device:
        l = torch.nn.Linear(256, 1024).to(device)
        weight = l.weight
        bias = l.bias
        x = torch.randn((s, b, hp))

    jitted = thunder.jit(f)
    computation_traces, *_ = thunder.compile_data(jitted).get_computation_and_inputs(x, weight, bias)
    print(computation_traces)
    y = jitted(x, weight, bias)


if __name__ == "__main__":
    main()
```

error message:
```
$ python megatron_core_col_linear_fwd.py
[NeMo W 2024-07-02 05:02:32 nemo_logging:349] /opt/pytorch/Megatron-LM/megatron/core/tensor_parallel/layers.py:279: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
      def forward(

[NeMo W 2024-07-02 05:02:32 nemo_logging:349] /opt/pytorch/Megatron-LM/megatron/core/tensor_parallel/layers.py:291: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
      def backward(ctx, grad_output):

[NeMo W 2024-07-02 05:02:32 nemo_logging:349] /opt/pytorch/Megatron-LM/megatron/core/tensor_parallel/layers.py:415: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
      def backward(ctx, grad_output):

[NeMo W 2024-07-02 05:02:34 nemo_logging:349] /opt/pytorch/Megatron-LM/megatron/core/dist_checkpointing/strategies/torch.py:20: DeprecationWarning: `torch.distributed._sharded_tensor` will be deprecated, use `torch.distributed._shard.sharded_tensor` instead
      from torch.distributed._sharded_tensor import ShardedTensor as TorchShardedTensor

[NeMo W 2024-07-02 05:02:42 nemo_logging:349] /opt/pytorch/lightning-thunder/thunder/torch/__init__.py:4942: torch._C._functorch.unwrap_if_dead has no effect under thunder.jit. `torch.autograd.Function.backward` is not respected by `thunder.jit`. `thunder.jit` generates backward based on the forward

Traceback (most recent call last):
  File "/opt/pytorch/lightning-thunder/megatron_core_col_linear_fwd.py", line 38, in <module>
    main()
  File "/opt/pytorch/lightning-thunder/megatron_core_col_linear_fwd.py", line 32, in main
    computation_traces, *_ = thunder.compile_data(jitted).get_computation_and_inputs(x, weight, bias)
  File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 223, in cache_info_wrapper
    res = fn(*args, **kwargs)
  File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 502, in get_computation_and_inputs
    jit_results: TraceResults = interpreter(
  File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 211, in _general_frontend
    return thunder_general_jit(fn, args, kwargs, sharp_edges=sharp_edges, record_history=record_history)
  File "/opt/pytorch/lightning-thunder/thunder/core/jit_ext.py", line 1719, in thunder_general_jit
    result = jfn(*args, **kwargs)
  File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6696, in fn_
    raise e
  File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6664, in fn_2
    return fn(*args, **kwargs)
  File "/opt/pytorch/lightning-thunder/megatron_core_col_linear_fwd.py", line 11, in f
    return LinearWithGradAccumulationAndAsyncCommunication.apply(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6189, in _call_dispatch
    opaque_result: Any = fn(*args_, **kwargs_)
  File "/opt/pytorch/Megatron-LM/megatron/core/tensor_parallel/layers.py", line 408, in forward
    output = torch.matmul(total_input, weight.t())
TypeError: matmul(): argument 'input' (position 1) must be Tensor, not TensorProxy
```

### Environment

- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:
    - NVIDIA/Megatron-LM      @ e33c8f78a35765d5aa37475a144da60e8a2349d1
    - NVIDIA/NeMo             @ 328185dd6c197100239bb8cd578f887105ed76fa
    - Dao-AILab/causal-conv1d @ f8c246707eff3431b5cf2ce6defa4b7f309ea9fb

**Comment by crcrpar** [comment]
It looks like that the use of `torch.matmul` in a custom `torch.autograd.Function.forward` is the culprit from the following snippet and its output.

If it's replaced with `total_input.matmul(weight.t())`, the script works.

```python
import torch

import thunder


class MyLinear(torch.autograd.Function):
    @staticmethod
    def forward(
        ctx,
        input: torch.Tensor,
        weight: torch.Tensor,
        bias: torch.Tensor,
        use_tensor_method: bool,
    ):
        ctx.save_for_backward(input, weight)
        ctx.use_bias = bias is not None
        total_input = input
        if use_tensor_method:
            output = total_input.matmul(weight.t())
        else:
            output = torch.matmul(total_input, weight.t())
        if bias is not None:
            output = output + bias
        return output

    @staticmethod
    def backward(ctx, grad_output):
        input, weight = ctx.saved_tensors
        use_bias = ctx.use_bias
        wgrad_compute = True
        if wgrad_compute:
            total_input = input
        grad_input = grad_output.matmul(weight)
        grad_weight = grad_output.t().matmul(total_input)
        grad_bias = grad_output.sum(dim=0) if use_bias else None
        return grad_input, grad_weight, grad_bias, None


class Model(torch.nn.Module):
    def __init__(self, use_tensor_method: bool = False):
        super().__init__()
        self.use_tensor_method = use_tensor_method
        self.l1 = torch.nn.Linear(12, 12)
    
    def forward(self, x):
        return MyLinear.apply(x, self.l1.weight, self.l1.bias, self.use_tensor_method)


if __name__ == "__main__":

    for use_tensor_method in (True, False):
        m = Model(use_tensor_method=use_tensor_method).to()
        j = thunder.jit(m)
        x = torch.randn(4, 12)

        print(f"### {use_tensor_method = }")
        try:
            y = j(x)
        except Exception as e:
            print(e)
        else:
            print(thunder.last_traces(j)[-1])
```

```
### use_tensor_method = True
/opt/pytorch/lightning-thunder/thunder/torch/__init__.py:4942: UserWarning: torch._C._functorch.unwrap_if_dead has no effect under thunder.jit. `torch.autograd.Function.backward` is not respected by `thunder.jit`. `thunder.jit` generates backward based on the forward
  warnings.warn(
# Constructed by Delete Last Used (took 0 milliseconds)
import torch
from torch import Tensor
from thunder.executors.torchex import no_autocast

@torch.no_grad()
@no_autocast
def augmented_forward_fn(x, arg, res):
  # x: "thunder.devices.Device(type='cpu') f32[4, 12]"
  # arg: "thunder.devices.Device(type='cpu') f32[12]"
  # res: "thunder.devices.Device(type='cpu') f32[12, 12]"
  t6 = torch.unsqueeze(arg, 0)  # t6: "thunder.devices.Device(type='cpu') f32[1, 12]"
    # t6 = ltorch.unsqueeze(arg, 0)  # t6: "thunder.devices.Device(type='cpu') f32[1, 12]"
      # t6 = prims.broadcast_in_dim(arg, [1, 12], [1])  # t6: "thunder.devices.Device(type='cpu') f32[1, 12]"
  t0 = torch.permute(res, (1, 0))  # t0: "thunder.devices.Device(type='cpu') f32[12, 12]"
    # t0 = ltorch.permute(res, (1, 0))  # t0: "thunder.devices.Device(type='cpu') f32[12, 12]"
      # t0 = prims.transpose(res, (1, 0))  # t0: "thunder.devices.Device(type='cpu') f32[12, 12]"
  t2 = Tensor.expand(t6, (4, 12))  # t2: "thunder.devices.Device(type='cpu') f32[4, 12]"
    # t2 = ltorch.expand(t6, (4, 12))  # t2: "thunder.devices.Device(type='cpu') f32[4, 12]"
      # t2 = prims.broadcast_in_dim(t6, (4, 12), (0, 1))  # t2: "thunder.devices.Device(type='cpu') f32[4, 12]"
  del t6
  t1 = torch.matmul(x, t0)  # t1: "thunder.devices.Device(type='cpu') f32[4, 12]"
    # t1 = ltorch.matmul(x, t0)  # t1: "thunder.devices.Device(type='cpu') f32[4, 12]"
      # t1 = prims.matmul(x, t0)  # t1: "thunder.devices.Device(type='cpu') f32[4, 12]"
  del t0
  t3 = torch.add(t1, t2)  # t3: "thunder.devices.Device(type='cpu') f32[4, 12]"
    # t3 = ltorch.add(t1, t2, alpha=None)  # t3: "thunder.devices.Device(type='cpu') f32[4, 12]"
      # t3 = prims.add(t1, t2)  # t3: "thunder.devices.Device(type='cpu') f32[4, 12]"
  del t1, t2
  return {'output': t3, 'flat_args': [x, arg, res], 'flat_output': (t3,)}, ((x,), ())
### use_tensor_method = False
matmul(): argument 'input' (position 1) must be Tensor, not TensorProxy
```

**Comment by crcrpar** [comment]
could you teach me why `total_input.matmul(weight.t())` works and `torch.matmul(total_input, weight.t())` not?

**Comment by t-vi** [comment]
I'm guessing you want the long explanation:
- The Thunder Python Interpreter will follow all calls to Python functions.
- C-implemented functions , however, are executed by calling them in CPython, and we lose control over the execution until the function returns,
- this implies that when we have a call sequence  Python -> C ->Python in the JIT, the "-> C -> Python" part will be outside our own interpretation. This happens for autograd.Function.apply (with the super implemented in C) calling to .forward,
- this in turn means that during execution of the forward, we don't have the JIT and we don't have the torch->thunder translation that the JIT effects,
- we do, however, have TensorProxies calls producing symbols even in a non-jitted environment (similar to the "CPYTHON" interpreter option).

The solution is to have a .apply lookaside closing the gap by calling `interpret_call(.forward, ...)` after setting things up.

**Comment by t-vi** [comment]
Repro without megatron:

```
import thunder, torch

class Fn(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        return 2 * torch.tanh(x)
    @staticmethod
    def backward(ctx, grad_out):
        return 2 * grad_out   # hahaha, not really

def fn(x):
    return Fn.apply(x)

a = torch.randn((1, 2), dtype=torch.float32)
thunder.jit(fn)(a)
```

Based on discussion with @crcrpar  (insights him, wrong leads me) for further investigation:
- apparently no lookasides are called for neither `torch.autograd.Function.apply` nor `torch._C._FunctionBase.apply`,
- The opaque function being called advertises itself as "built-in method apply of FunctionMeta object", but unfortunately, we don't have FunctionMeta.apply to work with.
- It could well be that class functions (which apply is) vs. super or vs. unbundling has a problem somewhere.

**Comment by t-vi** [comment]
Looking at this more, we can use a lookaside for `torch.autograd.Function.apply.__func__`. :sweat_smile: 
Apparently, we cannot easily unbundle class methods implemented in C, but here we can use the Python one further up the chain.
